name = "Tanaka"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
# description = ""
# homepage = ""
tags = ["blog", "syntax highlighting"]
features = ["blog", "syntax highlighting"]
min_version = "0.38"

[author]
  name = "brkcmd"
  # homepage = ""
